### PR TITLE
Relicense to MPL 2.0 as per issue #100

### PR DESCRIPTION
**Pull request by yarwelp**
Hello, I found your talk about this project after searching for _rust frp_ on YouTube. The talk convinced me to look into your library. Upon finding that it was licensed under GPL-3.0+, I was going to ask if you could change the license to something more permissive but then I found that you already had opened an issue (#100) about this yourself and agreed with the other contributors to go with MPL 2.0. Good choice :)

At the end of the conversation, you asked if anyone could submit a PR for the changes necessary. Here is my go at making such a PR. You will also note that I have bumped the version to v0.2.1. The reason for this bump is that IMO, a change of license warrants at least a minuscule version bump, so that any build systems which rely on version number are triggered to update. Not sure how crates.io works wrt this since I am still very much a newcommer to Rust. Hope this PR is good, let me know if there is anything in it that you would like to have different.

I have tagged this commit but I don't know if tags are included in pull requests or not.

### CODE REVIEW

**Comment by Moredread** [comment]
Besides that I think we should bump atleast to 0.3.0, I think this looks good. I don't know why Travis failed though, looks like a problem on their side...

**Comment by yarwelp** [comment]
At first I thought that the reason that Travis failed might be because of current Rust Nightly being incompatible in some regard with the Rust Nightly that was last run by Travis about three months ago for this repo. The job was using rustc 1.13.0-nightly (0be88eb79 2016-09-11) and cargo 0.13.0-nightly (398de25 2016-09-09). I was able to build it without trouble using rustc 1.13.0-nightly (5531c314a 2016-09-12) and cargo 0.13.0-nightly (b931a0f 2016-09-11), so I think it is like you said, @Moredread; a problem on the Travis end.

As for versioning, assuming semantic versioning is used, I suppose that depends on whether one considers the change of license a feature (minor) or a bugfix (minuscle) ;) Myself, I have no strong opinion on this and can submit another commit to this PR setting the version to whatever @aepsil0n would like it to be.

**Comment by yarwelp** [comment]
After merging a recent commit from master, checks are passing. Don't know if that is what fixed it or if the problem was temporary on Travis end. Either way, would you like to merge this now @aepsil0n ?

**Comment by milibopp** [comment]
I'm okay with a minor bump. This is mostly a legal nuisance anyway, nothing that breaks backwards compatibility. And we are pre 0.x anyway, so no actual guarantees. Thus merging…

@eriknstr, thank you for taking care of that. Do you happen to use it for anything, where LGPL would have been an issue or is it just house keeping?

**Comment by yarwelp** [comment]
Just house keeping :)

**Pull request merged**
