### PR TITLE
Relicense the software as LGPL 3.0+

### PR DESCRIPTION
**Pull request by milibopp**
This is something of a compromise, but still respects the user's rights more than MIT or BSD-like licenses.

### CODE REVIEW

**Comment by hseeberger** [comment]
Rust itself is licensed under Apache and MIT licenses. I'd rather follow.
Just my 2 cents.

**Comment by milibopp** [comment]
I don't think this is a candidate for inclusion in the standard library, which would be the only way Rust's license would be relevant here. Politically, LGPL is as far as I'm willing to go to be honest. Do you have any specific concerns? Note, that this was discussed in issue #6 motivating this change.

**Comment by Moredread** [comment]
(╯°□°)╯︵ ┻━┻

**Comment by mradke** [comment]
Just another note, because I stumbled over this:

The LGPL is incompatible with the Apple AppStore. So if you want to build a cross-plattform library in Rust for iOS you cannot use carboxyl for the project.

**Comment by Moredread** [comment]
is it really necessary to support a walled garden?

**Comment by milibopp** [comment]
No, not really. I my opinion this is the AppStore's problem, not mine. Personally, I do not care about iOS. And I'm certainly not going to let Apple dictate how to license this software.

**Comment by mradke** [comment]
>  I my opinion this is the AppStore's problem, not mine
> Yep. It is.
> 
> is it really necessary to support a walled garden?
> Nope. It is not.

 I just wanted to note this and it's good to get a clear position on this. Thanks @aepsil0n :+1:

**Comment by milibopp** [comment]
Yes, thanks for noting it. Sorry, that I got a little defensive about it. It can be hard to promote free software sometimes.

**Pull request merged**
