### PR TITLE
fixed a few clippy warnings

### PR DESCRIPTION
**Pull request by llogiq**
Just some style improvements. I also found a few problems in clippy :smile:

### CODE REVIEW

**Comment by Moredread** [comment]
What were the issues with clippy?

**Comment by llogiq** [comment]
#847-#849.

**Comment by Moredread** [comment]
Thanks :)

**Comment by llogiq** [comment]
Well, thank you for writing code that allowed me to find the issues :smile:

**Comment by milibopp** [comment]
Thanks for noticing! Never used clippy to look into these things. Overall this improves readibility.

**Comment by llogiq** [comment]
If you have a nightly Rust (and if not, I recommend https://rustup.rs), you can use clippy on your code with `cargo rustc -- -L /path/to/clippy/target/release -Z extra-plugins=clippy` (assuming you have checked out clippy in `/path/to/clippy` and built it with `cargo build --release`.

**Pull request merged**
